-- Q5. Function to return balance for a given account number

-- Create ACCOUNT table

CREATE TABLE ACCOUNT
(
    ACNO      NUMBER(5),
    CNAME     VARCHAR2(30),
    BNAME     VARCHAR2(30),
    BALANCE   NUMBER(12,2),
    CONSTRAINT PK_ACCOUNT PRIMARY KEY (ACNO)
);

INSERT INTO ACCOUNT VALUES (1001, 'ADITYA', 'SBI', 25000);
INSERT INTO ACCOUNT VALUES (1002, 'RAHUL', 'HDFC', 35000);
INSERT INTO ACCOUNT VALUES (1003, 'AMIT', 'ICICI', 45000);

COMMIT;

CREATE OR REPLACE FUNCTION GET_BALANCE
(
    P_ACNO IN NUMBER
)
RETURN NUMBER
IS
    V_BALANCE NUMBER;
BEGIN
    SELECT BALANCE
    INTO V_BALANCE
    FROM ACCOUNT
    WHERE ACNO = P_ACNO;

    RETURN V_BALANCE;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(
            -20002,
            'Account number ' || P_ACNO || ' not found.'
        );
END;
/